# Generated by Django 5.2.7 on 2025-10-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_document_created_by_remove_signer_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='api_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
